# Generated by Django 5.2.7 on 2025-10-13 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parent_alter_timecompletion_star_delete_userlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='one_star_time',
            field=models.IntegerField(default=45, help_text='Maximum time in seconds to get 1 star'),
        ),
        migrations.AddField(
            model_name='game',
            name='three_star_time',
            field=models.IntegerField(default=20, help_text='Maximum time in seconds to get 3 stars'),
        ),
        migrations.AddField(
            model_name='game',
            name='two_star_time',
            field=models.IntegerField(default=30, help_text='Maximum time in seconds to get 2 stars'),
        ),
        migrations.AlterField(
            model_name='timecompletion',
            name='star',
            field=models.IntegerField(choices=[(0, ' No Stars'), (1, ' 1 Star'), (2, ' 2 Stars'), (3, ' 3 Stars')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
