# Generated by Django 5.2.7 on 2025-10-16 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_difficulty_game_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecompletion',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child_time', to='api.userchild'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(choices=[('Shape', 'Shape'), ('Number', 'Number'), ('Alphabet', 'Alphabet'), ('Color', 'Color')], max_length=20),
        ),
    ]
