# Generated by Django 5.2.7 on 2025-10-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_timecompletion_child_alter_game_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecompletion',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child_name', to='api.userchild'),
        ),
    ]
